version: '3'
services:
  minio:
    image: minio/minio
    ports:
      - 9000:9000
    environment:
      - MINIO_ACCESS_KEY=minio1234567890
      - MINIO_SECRET_KEY=minio1234567890
    volumes:
      - ./data:/data
    command: server /data
